### ISSUE TITLE
关于解决jpg压缩噪点问题

### ISSUE THREAD

**Issue by xioxin** [xfgryujk/weibo-img-crypto#1]
在JPG上做的所有操作都是基于8x8像素块
如果不是按照像素打乱 而是按照8x8的像素块打乱
是否可以解决噪点问题

jpg压缩没有深入了解  这个方法可能并没有效果

**Comment by xfgryujk** [comment]
又想了一下也许可行，不过换算法又和以前不兼容了...
以后做个demo试试

**Comment by xioxin** [comment]
![image](https://user-images.githubusercontent.com/5716100/42746446-600b853c-890a-11e8-9022-bf463fdb21ac.png)
图片压缩后 放大后可以看出这些块
