### ISSUE TITLE
关于IOS系统使用的方法以及手机兼容问题

### ISSUE THREAD

**Issue by xioxin** [xfgryujk/weibo-img-crypto#11]
ios12中的捷径可以手动向网页中注入js代码

可以加载进去但是并不能用
![img_6033](https://user-images.githubusercontent.com/5716100/46066153-9696d780-c1a6-11e8-9237-3132eecc75de.jpg)

注入js脚本用的捷径脚本
https://www.icloud.com/shortcuts/e9e7d35de6b042e2aec8cca008940f57

我本打算通过捷径将相册中的图片进行解码 但我没办法调用到解码方法
能不能将加解密方法暴露到window中

**Comment by xfgryujk** [comment]
这个你fork一份自己修改就行了...

**Comment by xfgryujk** [comment]
而且微博的图床不允许weibo.cn跨域啊，这样JS拿不到图片数据
