### ISSUE TITLE
使用EXIF信息存储加密的seed,搭配chrome插件自动将页面上的加密后图片解密?

### ISSUE THREAD

**Issue by Illyrix** [xfgryujk/weibo-img-crypto#2]
如果渣浪不吞掉jpg的EXIF的话是否可以用EXIF存储代表已经加密过的flag和seed, 然后插件把加密图片都过滤出来并解密(不需要复制代码和手动右键了
当然如果渣浪吞了EXIF就不好做了

**Comment by xfgryujk** [comment]
我觉得会吞，至少加了水印的肯定会

**Comment by xfgryujk** [comment]
已经确认会被吞了，查看原图都没有
